### ISSUE TITLE
validate.php

### ISSUE THREAD

**Issue by AznoYT** [AznoYT/Stock-One#1]
Regardez le script pour la connexion database

**Comment by Tracks12** [comment]
Dit-moi peut tu me dire ce qu'il y a à faire pour la rentré en sin en ce
qui concerne notre projet s'il te plaît pck j'ai passer mon temps à avancer
le code depuis ces 3 derniers jours au lieux de m'occuper de ma diapo.

Merci d'avance

2016-12-02 16:21 GMT+01:00 Azno <notifications@github.com>:
