### ISSUE TITLE
validate.php insertion donnée

### ISSUE THREAD

**Issue by AznoYT** [AznoYT/Stock-One#2]
Regarde sur ton serveur si les données se rentre dans la database car je test ici: [teamwin.fr/sin](url) et sa marche pas, mais je cherche comment le réussir a le faire fonctionner

**Comment by Tracks12** [comment]
Ma db n'as aucun blem à gérer ton script gg mec, mais si tu veux je vais
essayer de l'optimiser à ma façon si ça te dérange pas

2016-12-10 11:34 GMT+01:00 Azno <notifications@github.com>:

**Comment by AznoYT** [comment]
Problème Corriger
