### ISSUE TITLE
Fichier Upload mais pas rentrer sur la base de donnée

### ISSUE THREAD

**Issue by AznoYT** [AznoYT/Stock-One#3]
https://gyazo.com/0bb2d11de3cb4d3c23dc62a98765b3ea

https://gyazo.com/d3878c759473fd6c18598b009a7dcdd0

**Comment by Tracks12** [comment]
T'as vérifier les paramètre de ta db ?

**Comment by AznoYT** [comment]
Ben elle enregistre les user mais pas les donnees c'est bizarre

**Comment by Tracks12** [comment]
Bon att je vais mettre une autre version de la db, et tu vas refaire le test

**Comment by Tracks12** [comment]
Récupère le nouveau sql que je viens d'upload et réessaie encore

**Comment by Tracks12** [comment]
Parce que mon upload se fait sans problème, il l'upload dans l'arborescence puis il le référence dans la db tranquillement

**Comment by AznoYT** [comment]
Je viens de mettre à jour mon serveur et c'est la même chose pour info j'utilise m'y sql 5.7

**Comment by Tracks12** [comment]
Tu peux pas switch sur un mysql qu'on utilise puis ensuite on résous tous les blems de bug ?

**Comment by Tracks12** [comment]
Ou alors si ça marche toujours pas tu refais la db au complète puis tu configure les chemin d'accès dans les fichiers php

**Comment by Tracks12** [comment]
Alors ?
